### PR TITLE
add sloth-alias.txt feature to generate materials with paths from other folders or other packages

### PR DESCRIPTION
**Pull request by illwieckz**
Load image aliases in `sloth-alias.txt` file.

File syntax is:

```
<basename1><space><vfspath1>
<basename2><space><vfspath2>
```

For example, if `textures/shared_exm_src/base1_d.png` exists,
and with those entries in `textures/shared_exm_src/sloth-alias.txt`:

```
base1_h.png textures/shared_ex_src/base1_h.png
base1_n.png textures/shared_ex_src/base1_n.png
base1_s.png textures/shared_ex_src/base1_s.png
```

Sloth will produce:

```
textures/shared_exm/base1
{
	qer_editorImage textures/shared_exm_src/base1_d.png

	{
		diffuseMap textures/shared_exm_src/base1_d.png
		normalMap textures/shared_ex_src/base1_n
		heightMap textures/shared_ex_src/base1_h
		specularMap textures/shared_ex_src/base1_s
	}
}
```

This makes possible for Sloth to generate materials with paths from other folders, or even from other packages.

### CODE REVIEW

**Comment by illwieckz** [comment]
I added two commits:

- do not analyze missing images, they can be aliases
- add explicit `additionGrayscale` option, useful when the addition map is an alias and can't be analyzed

This make it useful for `tex-ej01` to be handled by Sloth while deduplicating everything possible.

**Comment by slipher** [comment]
Why is the left side not a full path?

**Comment by illwieckz** [comment]
Sloth looks for file names in the given directory (so, not a full path), the left side gives the same result.

The `sloth-alias.txt` file is meant to be stored in the directory Sloth is listing files from, so Sloth already knows the directory path.

The original Sloth behaviour is to do that:

```
$ cd textures/shared_exm/base1
$ ls
base1_d.png
```

What I added to Sloth is to also do that:

```
$ cd textures/shared_exm/base1
$ cut -f1 -d' ' sloth.aliases
base1_h.png
```

In the end, sloths gets the `[ base1_d.png, base1_h.png ]` file list.

When writing the `.shader` file, if the image is not an alias, Sloth will write down `${dir}/$(basename "${file}"}`, and if the image is an alias, sloth will write `$(basename "${alias}"}`.

Sloth is directory-centric, you basically do `Sloth textures/shared_exm`, so Sloth doesn't know how to look for files outside of `textures/shared_exm`, this directory is then the best place to store the `sloth.aliases` file, and there can't be one `sloth-alias.txt` for multiple directories because of the way Sloth is already designed, and the parent directory is already known.

**Comment by illwieckz** [comment]
I renamed `sloth-alias.txt`. I think `sloth-<feature>.txt` is a good naming scheme for this and for future file likes this. Then the `.txt` extension is unique and openable by default on systems like Windows.

Another example of future file using that scheme can be a `sloth-relief.txt` that would list one height map per line with bias/scaling values.

**Comment by illwieckz** [comment]
This generic naming scheme also makes possible for Ucheon to ignore all of them even future ones we may decide to use:

- https://github.com/DaemonEngine/Urcheon/pull/67

**Pull request merged**
